//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservationSystem.Data.Repositories.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderFood
    {
        public int FoodId { get; set; }
        public string ItemName { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
