//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservationSystem.Data.Repositories.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int RoomId { get; set; }
        public string RoomNumber { get; set; }
        public string RoomType { get; set; }
        public string RoomStatus { get; set; }
        public decimal RoomPrice { get; set; }
        public int BedCount { get; set; }
        public int MaxGuests { get; set; }
        public string RoomDescription { get; set; }
    }
}
