using System;
using System.Windows.Forms;
using HotelReservationSystem.Domain.DTOs;
using HotelReservationSystem.Domain.Interface.CheckInOut;
using HotelReservationSystem.Domain.Model;
using HotelReservationSystem.Domain.Model.CheckInOut;
using static HotelReservationSystem.Domain.Enums.ReservationEnum;

namespace HotelReservationSystem.Presenter.Mapper
{
    public static class CheckInMapper
    {
        /// <summary>
        /// Maps from ICheckInOutView to CheckInOutModel (for saving)
        /// </summary>
        public static CheckInOutModel FromCheckInView(ICheckInOutView view)
        {
            if (view.AmountPaid < view.DownPayment)
            {
                MessageBox.Show("Amount paid cannot be less than the required down payment.",
                                "Payment Error",
                                MessageBoxButtons.OK,
                                MessageBoxIcon.Error);
                return null;
            }

            return new CheckInOutModel
            {
                CheckInId = 0, // Will be auto-generated by database
                ReservationId = string.IsNullOrEmpty(view.ReservationId) ? 0 : int.Parse(view.ReservationId),
                CustomerName = view.CustomerName,
                RoomType = view.RoomType,
                RoomNumber = view.RoomNumber,
                CheckInDate = view.CheckInDate,
                CheckOutDate = view.CheckOutDate,
                TimeArrival = view.TimeArrival,
                TotalPrice = view.TotalPrice,
                TotalCompanionCost = 0, // Will be calculated when companions are added
                DownPayment = view.DownPayment,
                AmountPaid = view.AmountPaid,
                CompanionCount = view.CompanionCount,
                PaymentMethod = view.PaymentMethod,
                PaymentReference = view.PaymentReference,
                PaymentStatus = Enum.TryParse<PaymentState>(view.PaymentStatus, out var status)
                    ? status
                    : PaymentState.Pending,
                ReservationStatus = view.ReservationStatus,
                IsCheckedIn = view.ReservationStatus == "CheckedIn",
                IsCheckedOut = view.ReservationStatus == "CheckedOut",
                ActualCheckIn = view.ReservationStatus == "CheckedIn" ? (DateTime?)DateTime.Now : null,
                ActualCheckOut = view.ReservationStatus == "CheckedOut" ? (DateTime?)DateTime.Now : null,
                CreatedAt = DateTime.Now
            };
        }

        /// <summary>
        /// Maps from ReservationModel to ICheckInOutView (for populating form from reservation)
        /// </summary>
        public static void ToCheckInView(ReservationModel model, ICheckInOutView view)
        {
            view.ReservationId = model.ReservationId > 0 ? model.ReservationId.ToString() : string.Empty;
            view.CustomerName = model.CustomerName ?? string.Empty;
            view.RoomType = model.RoomType ?? string.Empty;
            view.RoomNumber = model.RoomNumber ?? string.Empty;
            view.CheckInDate = model.CheckInDate != default ? model.CheckInDate : DateTime.Now;
            view.CheckOutDate = model.CheckOutDate != default ? model.CheckOutDate : DateTime.Now.AddDays(1);
            view.TimeArrival = model.TimeArrival != default ? model.TimeArrival : DateTime.Now;
            view.TotalPrice = model.TotalPrice;
            view.DownPayment = model.DownPayment;
            view.AmountPaid = model.AmountPaid;
            view.BalanceDue = model.BalanceDue;
            view.PaymentMethod = model.PaymentMethod ?? string.Empty;
            view.PaymentStatus = model.PaymentStatus.ToString();
            view.PaymentReference = model.PaymentReference ?? string.Empty;
            view.ReservationStatus = !string.IsNullOrEmpty(model.ReservationStatus) ? model.ReservationStatus : "CheckedIn";
            view.CompanionCount = 0;
        }

        /// <summary>
        /// Updates financial fields when price changes (e.g., room type/number change)
        /// </summary>
        public static void UpdateFinancialFields(ICheckInOutView view, decimal newTotalPrice)
        {
            decimal existingDownPayment = view.DownPayment;
            decimal existingAmountPaid = view.AmountPaid;

            view.TotalPrice = newTotalPrice;
            view.DownPayment = existingDownPayment;
            view.AmountPaid = existingAmountPaid;
            view.BalanceDue = newTotalPrice - existingAmountPaid;
        }

        /// <summary>
        /// Converts CheckInOutModel to CheckInDto for DataGrid display
        /// </summary>
        public static CheckInDto ToCheckInDto(CheckInOutModel model)
        {
            if (model == null) return null;

            return new CheckInDto
            {
                CheckInId = model.CheckInId,
                ReservationId = model.ReservationId,
                CustomerName = model.CustomerName ?? string.Empty,
                RoomNumber = model.RoomNumber ?? string.Empty,
                RoomType = model.RoomType ?? string.Empty,
                CheckInDate = model.CheckInDate,
                CheckOutDate = model.CheckOutDate,
                TimeArrival = model.TimeArrival,
                CompanionCount = model.CompanionCount,
                GrandTotal = model.GrandTotal,
                AmountPaid = model.AmountPaid,
                BalanceDue = model.BalanceDue,
                PaymentStatus = model.PaymentStatus.ToString(),
                ReservationStatus = model.ReservationStatus ?? "Pending",
                IsCheckedIn = model.IsCheckedIn,
                IsCheckedOut = model.IsCheckedOut,
                ActualCheckIn = model.ActualCheckIn
            };
        }
    }
}