//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservationSystem.Repositories.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billing
    {
        public int BillId { get; set; }
        public int ReservationId { get; set; }
        public string CustomerName { get; set; }
        public string RoomType { get; set; }
        public string RoomNumber { get; set; }
        public decimal TotalAmount { get; set; }
        public string PaymentStatus { get; set; }
        public System.DateTime DateBilled { get; set; }
    }
}
