//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservationSystem.Repositories.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfirmOrder
    {
        public int ServiceId { get; set; }
        public string ServiceType { get; set; }
        public string CustomerName { get; set; }
        public string RoomNumber { get; set; }
        public int TotalItems { get; set; }
        public string OrderStatus { get; set; }
        public decimal ServiceFee { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal GrandTotal { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
